module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
params:
  persons:
    thumbnail:
      desktop: "100x100"
      mobile: "100x100"
    image:
      desktop: "306x"
      mobile: "198x"
    post:
      desktop: "50x50"
      mobile: "50x50"
    publication:
      desktop: "50x50"
      mobile: "50x50"

# Default
permalinks:
  persons: /team/:slug/
